# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created: Wed Jun 19 21:24:50 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(831, 604)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabela = QtGui.QTableWidget(self.centralwidget)
        self.tabela.setGeometry(QtCore.QRect(70, 60, 321, 221))
        self.tabela.setObjectName(_fromUtf8("tabela"))
        self.tabela.setColumnCount(0)
        self.tabela.setRowCount(0)
        self.campo_estado = QtGui.QLineEdit(self.centralwidget)
        self.campo_estado.setGeometry(QtCore.QRect(10, 60, 41, 31))
        self.campo_estado.setObjectName(_fromUtf8("campo_estado"))
        self.campo_terminal = QtGui.QLineEdit(self.centralwidget)
        self.campo_terminal.setGeometry(QtCore.QRect(70, 20, 41, 31))
        self.campo_terminal.setObjectName(_fromUtf8("campo_terminal"))
        self.botao_estado = QtGui.QPushButton(self.centralwidget)
        self.botao_estado.setGeometry(QtCore.QRect(0, 90, 61, 31))
        self.botao_estado.setObjectName(_fromUtf8("botao_estado"))
        self.botao_terminal = QtGui.QPushButton(self.centralwidget)
        self.botao_terminal.setGeometry(QtCore.QRect(110, 20, 94, 27))
        self.botao_terminal.setObjectName(_fromUtf8("botao_terminal"))
        self.botao_determinizar = QtGui.QPushButton(self.centralwidget)
        self.botao_determinizar.setGeometry(QtCore.QRect(70, 290, 94, 27))
        self.botao_determinizar.setObjectName(_fromUtf8("botao_determinizar"))
        self.botao_minimizar = QtGui.QPushButton(self.centralwidget)
        self.botao_minimizar.setGeometry(QtCore.QRect(170, 290, 94, 27))
        self.botao_minimizar.setObjectName(_fromUtf8("botao_minimizar"))
        self.botao_inicial = QtGui.QPushButton(self.centralwidget)
        self.botao_inicial.setGeometry(QtCore.QRect(70, 320, 94, 27))
        self.botao_inicial.setObjectName(_fromUtf8("botao_inicial"))
        self.botao_final = QtGui.QPushButton(self.centralwidget)
        self.botao_final.setGeometry(QtCore.QRect(170, 320, 94, 27))
        self.botao_final.setObjectName(_fromUtf8("botao_final"))
        self.tabela2 = QtGui.QTableWidget(self.centralwidget)
        self.tabela2.setGeometry(QtCore.QRect(470, 60, 321, 221))
        self.tabela2.setObjectName(_fromUtf8("tabela2"))
        self.tabela2.setColumnCount(0)
        self.tabela2.setRowCount(0)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(540, 40, 151, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.botao_swap = QtGui.QPushButton(self.centralwidget)
        self.botao_swap.setGeometry(QtCore.QRect(410, 140, 41, 27))
        self.botao_swap.setObjectName(_fromUtf8("botao_swap"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(70, 350, 621, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.textEdit = QtGui.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(70, 390, 281, 91))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.botao_g_to_a = QtGui.QPushButton(self.centralwidget)
        self.botao_g_to_a.setGeometry(QtCore.QRect(70, 490, 181, 27))
        self.botao_g_to_a.setObjectName(_fromUtf8("botao_g_to_a"))
        self.botao_a_to_g = QtGui.QPushButton(self.centralwidget)
        self.botao_a_to_g.setGeometry(QtCore.QRect(70, 520, 181, 27))
        self.botao_a_to_g.setObjectName(_fromUtf8("botao_a_to_g"))
        self.botao_limpar_tela = QtGui.QPushButton(self.centralwidget)
        self.botao_limpar_tela.setGeometry(QtCore.QRect(270, 320, 101, 27))
        self.botao_limpar_tela.setObjectName(_fromUtf8("botao_limpar_tela"))
        self.textEdit_2 = QtGui.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(370, 390, 231, 91))
        self.textEdit_2.setObjectName(_fromUtf8("textEdit_2"))
        self.botao_salvar = QtGui.QPushButton(self.centralwidget)
        self.botao_salvar.setGeometry(QtCore.QRect(260, 20, 51, 27))
        self.botao_salvar.setObjectName(_fromUtf8("botao_salvar"))
        self.botao_carregar = QtGui.QPushButton(self.centralwidget)
        self.botao_carregar.setGeometry(QtCore.QRect(320, 20, 71, 27))
        self.botao_carregar.setObjectName(_fromUtf8("botao_carregar"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(480, 490, 121, 27))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.spinBox = QtGui.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(440, 490, 41, 27))
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(370, 500, 64, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(440, 520, 161, 27))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 370, 181, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(443, 370, 81, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.line_edit_ER1 = QtGui.QLineEdit(self.centralwidget)
        self.line_edit_ER1.setGeometry(QtCore.QRect(620, 390, 171, 27))
        self.line_edit_ER1.setObjectName(_fromUtf8("line_edit_ER1"))
        self.line_edit_ER2 = QtGui.QLineEdit(self.centralwidget)
        self.line_edit_ER2.setGeometry(QtCore.QRect(620, 420, 171, 27))
        self.line_edit_ER2.setObjectName(_fromUtf8("line_edit_ER2"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(650, 370, 101, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.botao_comparar_ER = QtGui.QPushButton(self.centralwidget)
        self.botao_comparar_ER.setGeometry(QtCore.QRect(620, 450, 111, 27))
        self.botao_comparar_ER.setObjectName(_fromUtf8("botao_comparar_ER"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 831, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.botao_estado, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.add_estado)
        QtCore.QObject.connect(self.botao_terminal, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.add_terminal)
        QtCore.QObject.connect(self.botao_determinizar, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.determinizar)
        QtCore.QObject.connect(self.botao_minimizar, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.minimizar)
        QtCore.QObject.connect(self.botao_inicial, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.set_initial)
        QtCore.QObject.connect(self.botao_final, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.set_final)
        QtCore.QObject.connect(self.botao_g_to_a, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.gramatica_para_automato)
        QtCore.QObject.connect(self.botao_swap, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.swap_tables)
        QtCore.QObject.connect(self.botao_a_to_g, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.automato_para_gramatica)
        QtCore.QObject.connect(self.botao_limpar_tela, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.limpar_tabela)
        QtCore.QObject.connect(self.botao_salvar, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.salvar)
        QtCore.QObject.connect(self.botao_carregar, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.carregar)
        QtCore.QObject.connect(self.pushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.listar_sentencas)
        QtCore.QObject.connect(self.pushButton_2, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.reconhecer_sentenca)
        QtCore.QObject.connect(self.botao_comparar_ER, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.comparar_ERs)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.botao_estado.setText(QtGui.QApplication.translate("MainWindow", "+Estado", None, QtGui.QApplication.UnicodeUTF8))
        self.botao_terminal.setText(QtGui.QApplication.translate("MainWindow", "+Terminal", None, QtGui.QApplication.UnicodeUTF8))
        self.botao_determinizar.setText(QtGui.QApplication.translate("MainWindow", "Determinizar", None, QtGui.QApplication.UnicodeUTF8))
        self.botao_minimizar.setText(QtGui.QApplication.translate("MainWindow", "Minimizar", None, QtGui.QApplication.UnicodeUTF8))
        self.botao_inicial.setText(QtGui.QApplication.translate("MainWindow", "Definir Inicial", None, QtGui.QApplication.UnicodeUTF8))
        self.botao_final.setText(QtGui.QApplication.translate("MainWindow", "Definir Final", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Autômato Resultante", None, QtGui.QApplication.UnicodeUTF8))
        self.botao_swap.setText(QtGui.QApplication.translate("MainWindow", "←→", None, QtGui.QApplication.UnicodeUTF8))
        self.botao_g_to_a.setText(QtGui.QApplication.translate("MainWindow", "Gramática para Automato", None, QtGui.QApplication.UnicodeUTF8))
        self.botao_a_to_g.setText(QtGui.QApplication.translate("MainWindow", "Autômato para Gramática", None, QtGui.QApplication.UnicodeUTF8))
        self.botao_limpar_tela.setText(QtGui.QApplication.translate("MainWindow", "Limpar Tabela", None, QtGui.QApplication.UnicodeUTF8))
        self.botao_salvar.setText(QtGui.QApplication.translate("MainWindow", "Salvar", None, QtGui.QApplication.UnicodeUTF8))
        self.botao_carregar.setText(QtGui.QApplication.translate("MainWindow", "Carregar", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Listar sentenças", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Tamanho", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("MainWindow", "Reconhecer Sentença", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Autômato ←→ Gramática", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Sentenças", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Comparar ERs", None, QtGui.QApplication.UnicodeUTF8))
        self.botao_comparar_ER.setText(QtGui.QApplication.translate("MainWindow", "Comparar ERs", None, QtGui.QApplication.UnicodeUTF8))

